services:
  - type: web
    name: arena-server
    runtime: node
    rootDir: ./arena-server
    buildCommand: npm install --production
    startCommand: node server.cjs
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: arena-frontend
    runtime: static
    buildCommand: npm install && npx vite build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_SERVER_URL
        value: https://arena-server-gh2h.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
